### ISSUE TITLE
Posting game script

### ISSUE THREAD

**Issue by ExcaliburZero** [Infinite-Dango-Studios/ganbatte-resources#1]
Currently, to my knowledge, we do not have any version of the script of the game online. Usually when Sabre-Hecate has finished a decent portion of the script he sends me a copy of the current script so I can code into the game the parts that he wrote. While this system of script distribution works, it is not a very efficient method.

The current method only allows the coder to look at the script, while it may be a good idea for the artists to look over it as well to get a better sense of the subjects they are drawing. It also is not very efficient as it works through email attachments rather than through Git + GitHub.

So I was thinking we may want to start hosting the script on GitHub through the resources repo (this repo), so that everyone can have quick and easy access to the script. Also, using Git will allow the script to be version controlled as well.

In terms of hosting the script, the script would likely need to be made into a normal ".txt" file rather than a Microsoft Word file. This could probably just be done by copying and pasting the entire script into a text editor like Notepad and saving it as a ".txt" file.

Does this sound like a good idea?

@Sabre-Hecate

**Comment by Sabre-Hecate** [comment]
Ok, not clear on what to do? Explain in simple numbered steps?

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
I think it will be easiest to add the script directly to the repo rather than using a fork an having to deal with pull requests, so the system will be a little bit different from how I showed you to deal with the Ganbatte repo.
1. Go to the resources repo page: https://github.com/Infinite-Dango-Studios/ganbatte-resources
2. Open the Command Line.
3. Enter: `cd documents`
4. Copy the HTTPS clone url.
5. Enter: `git clone HTTPS_URL_HERE`
6. Open the script file in Microsoft Word.
7. Open the Notepad program.
8. In Microsfot Word press Ctrl + A to select everything. Press Ctrl + C to copy everything.
9. Go to Notepad and Press Ctrl + V to paste everything from the script into Notepad.
10. Check over the formatting in Notepad, and see if everything looks fine in terms of being able to read where the lines begin and end.
11. Save the notepad file as "script.txt" in the new "ganbatte-resources" folder.
12. Close Microsoft Word and Notepad.
13. Go to the already open Command Line.
14. Enter: `cd ganbatte-resources`
15. Enter: `git status`
16. Enter: `git add script.txt`
17. Enter: `git commit -m "Added script file" -m "Added most recent script file."`
18. Enter: `git push origin master`

That should do it. Let me know if you have any questions or problems.

**Comment by Sabre-Hecate** [comment]
Posted it~!!!
